blog/urls.py
from django.urls import path, re_path

from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", index, name="index"),
    path("my-feed/", my_feed, name="my_feed"),
    path("<int:article_id>/", article, name="article"),
    path("<int:article_id>/comment/", add_comment, name="add_comment"),
    path("<int:article_id>/update/", update_article, name="update_article"),
    path("<int:article_id>/delete/", delete_article, name="delete_article"),
    path("create/", create_article, name="create_article"),
    path("topics/", all_topics, name="all_topics"),
    path("topics/<int:topic_id>/", articles_by_topic, name="articles_by_topic"),
    path("topics/<int:topic_id>/subscribe/", subscribe_topic, name="subscribe_topic"),
    path(
        "topics/<int:topic_id>/unsubscribe/",
        unsubscribe_topic,
        name="unsubscribe_topic",
    ),
    path("profile/", profile, name="profile"),
    path("register/", register, name="register"),
    path("set-password/", set_password, name="set_password"),
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout_view"),
    re_path(
        r"^(?P<year>\d{4})/(?P<month>\d{2})/$",
        articles_by_month,
        name="articles_by_month",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conf/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(default="There will be an article here soon...")
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to="photos/", blank=True, null=True)
    is_published = models.BooleanField(default=True)
    topics = models.ForeignKey(Topic, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(
        Article, related_name="comments", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user} on {self.article}"

blog/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpRequest

from .models import Topic, Article


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    topics = Topic.objects.all()
    articles = Article.objects.all()
    context = {"title": "Main Page", "topics": topics, "articles": articles}
    return render(request, "index.html", context)


def my_feed(request: HttpRequest) -> HttpResponse:
    return HttpResponse(
        "Page that will only contain articles on topics that the user is subscribed to!"
    )


def article(request: HttpRequest, article_id: int) -> HttpResponse:
    article = Article.objects.get(pk=article_id)
    context = {"title": "Detail Page", "article": article}
    return render(request, "detail_page.html", context)


def add_comment(request: HttpRequest, article_id: int) -> HttpResponse:
    return HttpResponse(f"This is comment for article #{article_id}.")


def update_article(request: HttpRequest, article_id: int) -> HttpResponse:
    return HttpResponse(f"This is page for update this article #{article_id}.")


def delete_article(request: HttpRequest, article_id: int) -> HttpResponse:
    context = {
        "title": "Delete Page",
    }
    return render(request, "delete_news.html", context)


def create_article(request: HttpRequest) -> HttpResponse:
    context = {
        "title": "Create Page",
    }
    return render(request, "add_news.html", context)


def all_topics(request: HttpRequest) -> HttpResponse:
    return HttpResponse("This is page for all topics")


def articles_by_topic(request: HttpRequest, topic_id: int) -> HttpResponse:
    articles = Article.objects.filter(topics_id=topic_id)
    topics = Topic.objects.all()
    context = {"title": articles[0].topics, "topics": topics, "articles": articles}
    return render(request, "index.html", context)


def subscribe_topic(request: HttpRequest, topic_id: int) -> HttpResponse:
    return HttpResponse("Address for subscribing to a specific topic")


def unsubscribe_topic(request: HttpRequest, topic_id: int) -> HttpResponse:
    return HttpResponse("Address for unsubscribing from a specific topic")


def profile(request: HttpRequest) -> HttpResponse:
    context = {
        "title": "Profile Page",
    }
    return render(request, "profile.html", context)


def register(request: HttpRequest) -> HttpResponse:
    context = {
        "title": "Register Page",
    }
    return render(request, "register.html", context)


def set_password(request: HttpRequest) -> HttpResponse:
    return HttpResponse("The page with the password change")


def login_view(request: HttpRequest) -> HttpResponse:
    context = {
        "title": "Login Page",
    }
    return render(request, "login.html", context)


def logout_view(request: HttpRequest) -> HttpResponse:
    return HttpResponse("Address to exit the site")


def articles_by_month(request: HttpRequest, year: int, month: int) -> HttpResponse:
    try:
        year = int(year)
        month = int(month)
    except ValueError:
        raise Http404("Incorrect date format")

    if month < 1 or month > 12:
        raise Http404("Incorrect month")

    current_date = datetime.now()

    if year > current_date.year or (
        year == current_date.year and month > current_date.month
    ):
        return HttpResponse(f"No articles for {year}/{month}")

    return HttpResponse(f"Articles for {year}/{month}.")

templates/add_news.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
  <div class="d-flex justify-content-center">
      <div class="card col-8 mb-4 mt-4">
          <div class="card-body">
              <h2 class="text-center">Add a new article</h2>
              <form action="" method="post" enctype="multipart/form-data">
                  <!--  Fields for filling-->
                  <div>
                      <input type="hidden" name="csrfmiddlewaretoken" value="1a7PHLHTRx8Sw0dH0fZEJhG0qmM6DgmHwSzhFvF16RnABVuToWnPfEFd2X58cUTj">
                      <p>
                          <label for="id_title">Article title:</label>
                          <input type="text" name="title" class="form-control" maxlength="255" required id="id_title">
                      </p>
                      <p>
                          <label for="id_content">Text of the article:</label>
                          <textarea name="content" cols="40" rows="10" class="form-control" required id="id_content">Soon everything will be...</textarea>
                      </p>
                      <p>
                          <label for="id_photo">Images:</label>
                          <input type="file" name="photo" class="form-control" accept="image/*" id="id_photo">
                      </p>
                      <p>
                          <label for="id_category">Category:</label>
                          <select name="category" class="form-control" required id="id_category">
                              <option value="" selected>---------</option>
                              <option value="1">First category</option>
                              <option value="2">First category</option>
                              <option value="3">First category</option>
                          </select>
                      </p>
                  </div>
                  <button class="btn btn-dark" type="submit">Add article</button>
              </form>
          </div>
      </div>
  </div>
  <div><div style="margin-top: 100px;"></div></div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <title>{% block title %}My Blog{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'navbar.html' %}      
       
        <!-- Main body-->
        <main>
          {% block main %}

          {% endblock %}
        </main>
        <!-- Footer-->
        {% include 'footer.html' %}
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>  
</body>
</html>

templates/delete_news.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
  <form action="" method="post">
      <input type="hidden" name="csrfmiddlewaretoken" value="KDXaXKY0oUqWrELDc7F0JdM5pXPEv6XBflpCVuW8DeFEwz2PAO3bfALi1y8G4Kud">
      <p>Are you sure you want to delete article with title: "article name"?</p>
      <div class="d-flex align-items-center">
        <input type="submit" value="Yes, delete" class="btn btn-danger">
        <a href="#!" class="btn btn-dark ms-3">Back</a>
      </div>
      
  </form>
  <div><div style="margin-top: 530px;"></div></div>
{% endblock %}

templates/detail_page.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
  <div class="d-flex justify-content-center"><div class="col-8">
      <div class="card"><div class="card-header d-flex justify-content-between align-items-center">{{ article.topics }}
          <div>
              <a href="#!" class="btn btn-dark">Delete</a>
              <a href="#!" class="btn btn-dark">Change</a>
              <a href="#!" class="btn btn-dark">Back</a>
          </div>
      </div>
          <img src="" class="card-img-top" alt="">
          
          <div class="card-body">
           {% if article.photo %}
           <img src="{{article.photo.url}}" width="300" alt="article">
           {% else %} 
          <img src="https://www.raumplus.ru/upload/iblock/99e/Skoro-zdes-budet-foto.jpg" width="300" alt="">
           {% endif %}
          <h5 class="card-title">{{ article }}</h5>
          <p class="card-text">{{ article.content |linebreaks }}</p>
      </div>
          <div class="card-footer d-flex justify-content-between"><p class="card-text">{{ article.created_at | date:"d/m/Y H:i" }}</p>
              <a href="#">Author of the article: {{ article.author }}</a>
          </div>
      </div>
      <hr>

      <!--  reviews-->
      <form action="#!" method="post" , enctype="multipart/form-data">
          <input type="hidden" name="csrfmiddlewaretoken" value="dVpvJs374bq08P5ZzKsB7pSNUnoJ6PXRIDRXHc1fjvFIdKmbXrQMDMR0wYHLFtut">
          <textarea name="text" cols="40" rows="10" class="form-control" placeholder="Текст вашего комментария" required id="id_text"></textarea>
          <button class="btn btn-dark mt-2" type="submit">Add a comment</button>
      </form>

      <div class="card mt-2"><h5 class="card-header">Some person</h5>
          <div class="card-body">
              <p class="card-text">Review text</p>
          </div>
      </div>
  </div>
  </div>
{% endblock %}

templates/footer.html
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0);">© 2024 Copyright:<a class="text-dark" href="https://github.com/mikimoern"> Alexandru Cordunian</a>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}

{% block title %}{{ title}}{% endblock %}

{% block main %}
  <h2>News portal</h2>
  <div class="d-flex justify-content-between">
      <div class="col-3">
          <!-- Sidebar-->
           {% for topic in topics %}
          <div class="list-group">
              <a href="{% url 'articles_by_topic' topic.pk %}" class="list-group-item list-group-item-action">{{ topic }}</a>
          </div>
          {% endfor %}
      </div>
      <!-- Posts-->
      <div class="col-8">
          <!-- Post-->
          {% for article in articles %}
          <div class="card"><div class="card-header text-center">{{ article.topics }}</div>
              <div class="card-body"><h5 class="card-title text-center">{{ article }}</h5><p class="card-text">{{ article.content | truncatewords:30 }}</p><a href="{% url 'article' article.pk %}" class="btn btn-primary">Reed more</a></div>
              <div class="card-footer text-muted text-end">{{ article.created_at | date:"d/m/Y H:i" }}</div>
          </div>
          {% endfor %}
         
      </div>
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
   <div><div style="margin-top: 100px;"></div></div>
    <div class="d-flex justify-content-center">
        <div class="card col-4 mb-4 mt-4">
            <div class="card-body">
                <h2 class="text-center">Login to account</h2>
                <form action="" method="post">
                    <input type="hidden" name="csrfmiddlewaretoken" value="641UKkkPe6PZgy91w6Roc3RvtNzVxAONBMtmI4iXtq4HltqdUNfzIqQI5oSX6elp">
                    <p>
                        <label for="id_username">Username:</label>
                        <input type="text" name="username" class="form-control" maxlength="150" required id="id_username">
                    </p>
                    <p>
                        <label for="id_password">Password:</label>
                        <input type="password" name="password" class="form-control" required id="id_password">
                    </p>
                    <button class="btn btn-dark" type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
    <div><div style="margin-top: 180px;"></div></div>
{% endblock %}

templates/navbar.html
 {% load static %}
 <header>
    <div class="container">
        <!--   Header-->
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'images/blog.png' %}" width="32" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav"><li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a></li></ul>
                    
                    <form class="d-flex" role="search" method="get" action="#!">
                        <input name="q" class="form-control me-2" type="search" placeholder="Serach" aria-label="Serach">
                        <button class="btn btn-outline-success" type="submit">Serach</button>
                    </form>
                    <ul class="navbar-nav">
                        <!--  Users-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Hello User
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">My page</a></li>
                                <li><a class="dropdown-item" href="#!">Add article</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#!">Exit</a></li>
                            </ul>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </div>
</header>

templates/profile.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
  <div class="container">
      <div class="main-body">
        <div class="row gutters-sm">
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                  <img src="https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" alt="Admin" class="rounded-circle" width="150">
                  <div class="mt-3">
                    <h4>John Smith</h4>
                    <p class="text-secondary mb-1">Python Developer</p>
                    <p class="text-muted font-size-sm">Prague, Czeh Republic</p>
                    <button class="btn btn-primary">Follow</button>
                    <button class="btn btn-outline-primary">Message</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card mb-3">
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Full name</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    John Smith
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Email</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    John Smith email
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Phone</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    +99 (899) 98989898
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Address</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    Tashkent, Uzbekistan
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-12">
                    <a class="btn btn-info " target="__blank" href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                  </div>
                </div>
              </div>
            </div>
              
          </div>
        </div>
      </div>
  </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block main %}
  <div class="d-flex justify-content-center">
    <div class="card col-4 mb-4 mt-4">
        <div class="card-body">
            <h2 class="text-center">Register an account</h2>
            <form action="" method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="bIz3P1xxc8nihUSxXhkEl8rSmEIZ9fA8Gq1vNLvFrsC0mP9JlYIPRvq5Yf11IT7K">
                <div class="form-floating flex-fill mb-4">
                    <input type="text" name="username" class="form-control" placeholder="User name" maxlength="150" autofocus required id="id_username">
                    <label for="id_username">
                        <i class="fa-solid fa-user"></i>  User name
                    </label>
              </div>
              <div class="form-floating flex-fill mb-4">
                  <input type="email" name="email" class="form-control" placeholder="E-mail" required id="id_email">
                  <label for="id_email">
                      <i class="fa-solid fa-envelope"></i>  E-mail
                  </label>
              </div>
              <div class="form-floating flex-fill mb-4">
                  <input type="password" name="password1" class="form-control" placeholder="Password" required id="id_password1">
                  <label for="">
                      <i class="fa-solid fa-key"></i>  Password
                  </label>
              </div>
                <div class="form-floating flex-fill mb-4">
                  <input type="password" name="password2" class="form-control" placeholder="Confirm password" required id="id_password2">
                  <label for="">
                      <i class="fa-solid fa-key"></i>  Confirm password
                  </label>
              </div>
                <button class="btn btn-dark" type="submit">Registration</button>
            </form>
        </div>
        </div>
    </div>
    <div><div style="margin-top: 100px;"></div></div>
{% endblock %}